Format and path options
matugm/visual-call-graph pull request #1
Opened 2019-03-07 03:03 UTC by 7sedam7

Especially when using this on a big trace path, the png image is unusable and svg fits better.
To not limit to any of the choices I'm proposing to have an option to set it, but still, leave the default as you made it.

2019-03-07 05:20 UTC, 7sedam7 commented
@matugm Can you please take a look and merge if it's ok :)

2019-03-07 12:01 UTC, matugm requested changes

2019-03-07 12:01 UTC, matugm commented on lib/visual_call_graph/graph_manager.rb
> +    @g.output(format.to_sym => path)
Can you add a blank line between the local variables & the method call? I think it makes the code easier to read :)

2019-03-08 03:54 UTC, 7sedam7 commented
good suggestion @matugm and done :)

2019-03-08 15:01 UTC, matugm approved these changes

2019-03-08 19:33 UTC, 7sedam7 commented
Thanks for the approve, can you merge please :)

2019-03-08 20:53 UTC, merged